In [6]:
import pandas as pd
from utils import *
import numpy as np
from viz import limb_names, connections
from viz import *

# Read the Parquet file
df = pd.read_parquet('/Users/timpoux-guillaume/Downloads/NBA-jadal/nba_game_0022300528_processed.parquet')



df.head()  

output_dir = "/Users/timpoux-guillaume/Downloads/NBA-jadal/test"

distances_to_calculate = list(limb_names.keys())
# distances_to_calculate= [
#     'l_upperarm',  # 'l_distance_shoulder_elbow'
#     'r_upperarm',  # 'r_distance_shoulder_elbow'
#     'r_pinky_len',  # 'r_distance_wrist_pinky'
#     'l_pinky_len',  # 'l_distance_wrist_pinky'
#     'l_thumb_len',  # 'l_distance_wrist_thumb'
#     'r_thumb_len',  # 'r_distance_wrist_thumb'
#     'l_innerfoot',  # 'l_distance_heel_bigtoe'
#     'r_innerfoot',  # 'r_distance_heel_bigtoe'
#     'l_outerfoot',  # 'l_distance_heel_smalltoe'
#     'r_outerfoot',  # 'r_distance_heel_smalltoe'
#     'r_collar',     # 'r_distance_neck_shoulder'
#     'l_collar',     # 'l_distance_neck_shoulder'
#     'l_forearm',    # 'l_distance_elbow_wrist'
#     'r_forearm'     # 'r_distance_elbow_wrist'
# ]

num_frames = 1000

# Set the maximum number of columns to display to None, which means display all columns
pd.set_option('display.max_columns', None)

df.head()

,frame,period,timeUTC,gameClockTime,gameClockRunning,shotClockTime,shotClockRunning,ball_x,ball_y,ball_z,player_id,fullName,jersey_number,team_id,centroid_x,centroid_y,centroid_z,lAnkle_x,lAnkle_y,lAnkle_z,lEar_x,lEar_y,lEar_z,lElbow_x,lElbow_y,lElbow_z,lEye_x,lEye_y,lEye_z,lHip_x,lHip_y,lHip_z,lKnee_x,lKnee_y,lKnee_z,lShoulder_x,lShoulder_y,lShoulder_z,lWrist_x,lWrist_y,lWrist_z,neck_x,neck_y,neck_z,nose_x,nose_y,nose_z,rAnkle_x,rAnkle_y,rAnkle_z,rEar_x,rEar_y,rEar_z,rElbow_x,rElbow_y,rElbow_z,rEye_x,rEye_y,rEye_z,rHip_x,rHip_y,rHip_z,rKnee_x,rKnee_y,rKnee_z,rShoulder_x,rShoulder_y,rShoulder_z,rWrist_x,rWrist_y,rWrist_z,midHip_x,midHip_y,midHip_z,lHeel_x,lHeel_y,lHeel_z,lBigToe_x,lBigToe_y,lBigToe_z,lSmallToe_x,lSmallToe_y,lSmallToe_z,lThumb_x,lThumb_y,lThumb_z,lPinky_x,lPinky_y,lPinky_z,rHeel_x,rHeel_y,rHeel_z,rBigToe_x,rBigToe_y,rBigToe_z,rSmallToe_x,rSmallToe_y,rSmallToe_z,rThumb_x,rThumb_y,rThumb_z,rPinky_x,rPinky_y,rPinky_z
0,1,1,2024-01-12T00:35:40.688Z,12:00,0,24,0,37.614,-49.307,44.386,1628369,Jayson Tatum,0,1610612738,16.376,113.199,19.082,24.551,110.000,7.417,20.391,86.603,35.100,30.131,96.105,18.798,17.973,84.788,30.713,20.416,113.622,19.454,32.309,96.500,19.481,23.993,94.225,31.593,28.469,92.540,6.916,16.592,93.921,32.608,16.715,86.516,29.481,9.313,109.631,7.623,13.313,86.517,35.321,4.245,93.430,17.673,15.338,84.794,30.784,12.354,112.867,18.490,0.556,95.679,18.424,9.446,94.148,30.990,5.670,91.165,5.554,16.359,113.108,19.301,22.160,112.288,4.341,28.062,102.911,-0.043,29.443,105.771,0.098,26.002,91.499,4.605,28.658,93.030,2.245,11.530,112.006,5.094,6.188,103.138,-0.518,4.872,106.015,-0.039,6.962,89.636,2.637,5.444,86.593,4.482
1,1,1,2024-01-12T00:35:40.688Z,12:00,0,24,0,37.614,-49.307,44.386,1627736,Malik Beasley,5,1610612749,-20.522,-113.595,38.638,-34.173,-110.838,5.161,-21.449,-95.561,64.596,-30.136,-108.081,48.070,-19.314,-91.481,61.916,-24.575,-113.712,39.079,-29.426,-108.848,22.628,-25.666,-100.051,56.938,-28.410,-106.611,38.205,-18.834,-99.851,57.598,-18.409,-92.104,59.706,-7.683,-112.784,4.895,-14.429,-95.823,63.707,-4.812,-107.752,47.946,-16.706,-91.601,61.553,-16.501,-113.491,37.962,-10.668,-107.730,22.132,-11.648,-101.613,56.818,0.987,-101.260,42.951,-20.490,-113.582,38.873,-34.563,-112.293,0.902,-32.576,-100.587,1.904,-35.542,-101.732,1.908,-26.331,-104.720,36.056,-28.902,-106.164,33.551,-8.151,-113.946,0.973,-6.642,-102.324,2.117,-4.252,-104.421,1.764,1.629,-98.002,41.730,4.412,-100.036,39.972
2,1,1,2024-01-12T00:35:40.688Z,12:00,0,24,0,37.614,-49.307,44.386,1628401,Derrick White,9,1610612738,186.762,5.580,33.534,182.000,-11.895,5.294,165.293,1.057,56.513,177.180,-6.285,39.093,161.137,3.439,54.181,187.355,1.564,33.923,176.479,-7.444,22.834,170.224,-2.030,49.515,175.509,-7.069,27.423,169.528,5.181,50.247,161.740,4.780,52.199,179.707,22.189,4.745,165.162,8.123,56.972,175.847,16.433,38.417,161.112,6.072,54.320,186.224,9.576,32.914,174.863,19.083,22.769,170.226,11.764,49.449,174.092,18.446,27.010,186.706,5.601,33.764,184.119,-11.722,1.308,172.326,-13.229,0.512,174.268,-15.738,0.730,174.173,-6.183,24.269,175.658,-9.675,23.513,181.289,22.202,0.944,170.171,26.071,1.252,172.738,27.946,1.616,172.744,17.383,23.916,174.479,20.687,22.895
3,1,1,2024-01-12T00:35:40.688Z,12:00,0,24,0,37.614,-49.307,44.386,1627759,Jaylen Brown,7,1610612738,12.135,-117.351,41.491,0.891,-113.706,5.354,10.673,-90.632,58.495,1.442,-105.828,43.157,14.450,-88.354,55.505,8.083,-116.968,41.230,4.043,-108.652,22.951,6.742,-99.371,54.669,1.862,-98.788,40.063,13.970,-97.755,54.948,15.751,-89.956,54.153,20.074,-112.409,5.793,17.347,-92.083,60.366,21.399,-104.266,40.068,16.932,-88.928,56.180,16.185,-117.826,41.533,18.317,-107.915,23.733,20.962,-97.864,52.762,19.236,-104.696,32.759,12.136,-117.258,41.710,0.741,-115.184,1.087,0.808,-103.316,2.148,-1.934,-104.925,2.144,5.343,-99.352,40.350,4.833,-99.667,36.527,19.936,-114.260,2.118,20.067,-102.514,1.286,22.694,-104.340,1.372,16.785,-104.230,30.251,19.619,-105.930,28.239
4,1,1,2024-01-12T00:35:40.688Z,12:00,0,24,0,37.614,-49.307,44.386,203081,Damian Lillard,0,1610612749,-316.522,-10.626,36.134,-302.523,-11.460,5.530,-312.203,-8.379,68.012,-316.452,2.123,48.462,-307.681,-11.037,67.077,-315.195,-6.773,35.981,-306.807,-8.969,22.319,-312.564,-4.231,57.990,-315.762,2.478,37.640,-313.868,-10.953,59.962,-307.540,-11.998,64.809,-325.651,-11.358,4.667,-312.881,-15.381,67.197,-321.016,-24.662,49.944,-307.942,-13.637,66.736,-317.749,-14.515,36.075,-317.323,-13.225,19.952,-317.036,-17.683,58.984,-311.584,-22.116,45.438,-316.622,-10.590,36.347,-303.278,-12.269,1.149,-291.775,-12.506,4.249,-293.152,-9.787,3.344,-316.060,0.529,34.702,-317.569,3.897,33.538,-327.341,-11.255,0.915,-315.573,-11.540,0.591,-317.434,-14.142,0.638,-309.395,-19.428,44.732,-309.249,-21.419,41.417

In [10]:
import plotly.graph_objects as go
start_frame = 201460
num_frames = 100

# Filter the dataframe for the player with player_id 1628369
df = df[df['player_id'] == 1628369]
reduced_df = df[(df['frame'] >= start_frame) & (df['frame'] < start_frame + num_frames)]

reduced_df

,frame,period,timeUTC,gameClockTime,gameClockRunning,shotClockTime,shotClockRunning,ball_x,ball_y,ball_z,player_id,fullName,jersey_number,team_id,centroid_x,centroid_y,centroid_z,lAnkle_x,lAnkle_y,lAnkle_z,lEar_x,lEar_y,lEar_z,lElbow_x,lElbow_y,lElbow_z,lEye_x,lEye_y,lEye_z,lHip_x,lHip_y,lHip_z,lKnee_x,lKnee_y,lKnee_z,lShoulder_x,lShoulder_y,lShoulder_z,lWrist_x,lWrist_y,lWrist_z,neck_x,neck_y,neck_z,nose_x,nose_y,nose_z,rAnkle_x,rAnkle_y,rAnkle_z,rEar_x,rEar_y,rEar_z,rElbow_x,rElbow_y,rElbow_z,rEye_x,rEye_y,rEye_z,rHip_x,rHip_y,rHip_z,rKnee_x,rKnee_y,rKnee_z,rShoulder_x,rShoulder_y,rShoulder_z,rWrist_x,rWrist_y,rWrist_z,midHip_x,midHip_y,midHip_z,lHeel_x,lHeel_y,lHeel_z,lBigToe_x,lBigToe_y,lBigToe_z,lSmallToe_x,lSmallToe_y,lSmallToe_z,lThumb_x,lThumb_y,lThumb_z,lPinky_x,lPinky_y,lPinky_z,rHeel_x,rHeel_y,rHeel_z,rBigToe_x,rBigToe_y,rBigToe_z,rSmallToe_x,rSmallToe_y,rSmallToe_z,rThumb_x,rThumb_y,rThumb_z,rPinky_x,rPinky_y,rPinky_z
1362864,201460,2,2024-01-12T01:31:38.013Z,4.8,0,None,0,560.566,-16.166,50.332,1628369,Jayson Tatum,0,1610612738,459.026,130.183,39.730,457.598,123.533,6.817,458.257,127.730,73.176,467.469,129.773,51.710,458.182,122.418,72.772,462.894,128.912,39.979,458.834,119.199,25.637,462.695,127.763,64.820,466.087,118.605,49.600,455.034,127.093,65.212,457.373,121.595,70.591,458.189,144.707,5.799,451.830,124.781,72.783,446.522,128.053,48.735,455.790,121.327,72.587,455.148,131.356,39.265,455.492,133.970,21.671,447.729,127.293,62.759,452.499,118.980,45.440,459.038,130.281,39.946,457.554,126.088,3.091,453.730,114.929,1.410,456.813,115.645,1.112,463.989,115.767,49.846,466.294,114.757,46.907,459.071,146.648,2.277,454.660,135.867,0.543,452.885,138.518,0.792,455.514,117.135,45.560,454.090,116.044,42.132
1362874,201461,2,2024-01-12T01:31:38.029Z,4.8,0,None,0,561.897,-16.242,50.798,1628369,Jayson Tatum,0,1610612738,459.217,130.405,39.857,458.638,123.641,6.989,458.468,127.888,73.281,467.597,130.266,51.921,458.402,122.577,72.850,463.114,129.231,40.123,459.544,119.260,25.839,462.836,128.178,65.001,466.294,118.969,50.418,455.191,127.286,65.338,457.580,121.764,70.670,458.177,144.737,5.758,452.045,124.926,72.918,446.735,127.869,48.828,456.011,121.482,72.676,455.312,131.479,39.376,455.663,134.174,21.803,447.909,127.251,62.841,453.067,118.813,46.135,459.225,130.504,40.073,458.602,126.252,3.302,454.913,115.081,1.413,457.991,115.835,1.155,464.264,116.109,50.876,466.553,114.960,47.977,459.066,146.579,2.185,454.654,135.757,0.743,452.880,138.414,0.915,456.131,117.070,46.437,454.849,115.771,43.025
1362884,201462,2,2024-01-12T01:31:38.046Z,4.8,0,None,0,563.165,-16.205,51.371,1628369,Jayson Tatum,0,1610612738,459.370,130.583,40.020,459.780,123.846,7.116,458.749,128.020,73.428,467.761,130.714,52.165,458.648,122.712,72.975,463.299,129.525,40.295,460.320,119.407,25.990,463.019,128.560,65.219,466.487,119.342,51.113,455.390,127.471,65.515,457.798,121.913,70.800,458.160,144.729,5.826,452.306,125.098,73.117,447.010,127.687,48.995,456.248,121.631,72.820,455.436,131.540,39.529,455.785,134.236,21.965,448.135,127.214,62.996,453.627,118.660,46.856,459.375,130.683,40.235,459.741,126.500,3.460,456.318,115.276,1.387,459.383,116.098,1.183,464.511,116.475,51.739,466.784,115.221,48.870,459.092,146.520,2.237,454.674,135.686,0.897,452.903,138.349,1.013,456.723,117.013,47.323,455.574,115.530,43.939
1362894,201463,2,2024-01-12T01:31:38.063Z,4.8,0,None,0,564.182,-15.927,51.843,1628369,Jayson Tatum,0,1610612738,459.514,130.767,40.165,460.961,124.058,7.222,458.954,128.148,73.593,467.891,131.098,52.348,458.866,122.841,73.124,463.468,129.804,40.444,461.147,119.621,26.098,463.218,128.827,65.391,466.677,119.677,51.767,455.604,127.614,65.674,458.021,122.046,70.946,458.132,144.681,5.881,452.518,125.211,73.266,447.248,127.474,49.168,456.470,121.755,72.964,455.559,131.630,39.670,455.897,134.350,22.139,448.351,127.179,63.161,454.150,118.539,47.576,459.517,130.868,40.380,460.940,126.742,3.587,457.630,115.509,1.386,460.690,116.356,1.222,464.806,116.787,52.580,467.067,115.454,49.738,459.078,146.448,2.285,454.694,135.594,1.001,452.915,138.253,1.089,457.274,116.988,48.170,456.229,115.341,44.828
1362904,201464,2,2024-01-12T01:31:38.079Z,4.8,0,None,0,564.964,-15.584,52.628,1628369,Jayson Tatum,0,1610612738,459.642,130.877,40.331,462.283,124.357,7.278,459.215,128.199,73.792,468.037,131.468,52.550,459.069,122.895,73.305,463.616,130.004,40.606,462.013,119.900,26.144,463.461,129.027,65.581,466.878,120.021,52.369,455.862,127.730,65.871,458.215,122.118,71.124,458.082,144.584,6.002,452.747,125.334,73.454,447.509,127.285,49.403,456.660,121.836,73.140,455.667,131.649,39.841,455.973,134.357,22.337,448.605,127.159,63.384,454.630,118.434,48.330,459.643,130.979,40.546,462.301,127.059,3.657,459.165,115.800,1.338,462.217,116.683,1.237,465.100,117.125,53.354,467.332,115.721,50.523,459.051,146.360,2.417,454.710,135.495,1.079,452.923,138.149,1.157,457.767,116.968,49.053,456.828,115.171,45.758
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1363814,201555,2,2024-01-12T01:31:39.596Z,4.8,0,None,0,509.140,-69.637,69.956,1628369,Jayson Tatum,0,1610612738,452.864,127.680,40.833,469.635,125.635,9.491,452.129,124.392,74.268,459.654,119.639,51.813,448.110,120.894,74.180,455.901,124.960,40.954,458.478,120.171,23.858,455.347,120.779,65.351,458.550,115.019,41.067,449.316,125.871,66.262,446.905,120.814,72.029,452.117,131.444,5.728,445.640,127.197,73.856,444.702,134.442,50.316,445.699,121.940,73.988,449.770,130.317,40.497,446.993,126.218,23.254,444.238,131.412,64.235,441.502,132.357,39.309,452.921,127.763,41.049,472.160,128.707,7.348,468.440,119.752,0.424,471.178,119.531,2.024,456.634,115.096,38.094,460.230,114.926,36.677,453.820,132.335,2.087,445.325,124.222,1.263,444.825,127.376,1.059,441.735,130.107,36.589,441.831,133.518,34.766
1363824,201556,2,2024-01-12T01:31:39.613Z,4.8,0,None,0,504.042,-72.767,70.186,1628369,Jayson Tatum,0,1610612738,452.283,127.716,40.899,468.784,125.392,9.743,451.597,124.547,74.358,459.002,119.654,51.934,447.592,121.033,74.274,455.269,124.940,41.015,457.415,119.921,23.939,454.726,120.848,65.462,457.797,115.063,41.171,448.763,126.023,66.358,446.384,120.950,72.124,452.079,131.483,5.773,445.095,127.325,73.960,444.176,134.696,50.435,445.176,122.069,74.086,449.238,130.410,40.569,446.778,126.367,23.279,443.725,131.596,64.324,440.913,132.712,39.414,452.342,127.798,41.114,471.383,128.472,7.702,467.626,119.726,0.535,470.339,119.429,2.166,455.880,115.192,38.201,459.470,114.952,36.779,453.810,132.369,2.144,445.346,124.227,1.275,444.839,127.379,1.058,441.130,130.480,36.678,441.266,133.903,34.880
1363834,201557,2,2024-01-12T01:31:39.629Z,4.8,0,None,0,498.875,-75.893,70.355,1628369,Jayson Tatum,0,1610612738,451.734,127.747,40.961,467.875,125.158,9.938,451.070,124.694,74.447,458.360,119.658,52.054,447.081,121.164,74.355,454.665,124.913,41.073,456.337,119.724,24.010,454.119,120.907,65.573,457.040,115.114,41.270,448.233,126.173,66.449,445.873,121.080,72.205,452.055,131.502,5.811,444.557,127.446,74.052,443.653,134.941,50.541,444.660,122.190,74.169,448.741,130.499,40.635,446.586,126.523,23.303,443.235,131.779,64.403,440.312,133.052,39.513,451.795,127.828,41.176,470.549,128.220,7.968,466.650,119.688,0.621,469.347,119.305,2.260,455.121,115.301,38.304,458.703,114.984,36.875,453.815,132.380,2.194,445.361,124.235,1.274,444.854,127.386,1.046,440.504,130.837,36.762,440.676,134.271,34.987
1363844,201558,2,2024-01-12T01:31:39.646Z,4.8,0,None,0,493.697,-79.022,70.395,1628369,Jayson Tatum,0,1610612738,451.225,127.772,41.015,466.925,124.939,10.060,450.544,124.833,74.530,457.731,119.647,52.169,446.568,121.288,74.418,454.099,124.880,41.125,455.265,119.593,24.064,453.522,120.953,65.678,456.285,115.168,41.359,447.723,126.322,66.528,445.366,121.205,72.264,452.062,131.504,5.836,444.022,127.562,74.125,443.138,135.174,50.627,444.144,122.306,74.228,448.289,130.584,40.690,446.426,126.689,23.319,442.767,131.963,64.464,439.702,133.377,39.598,451.289,127.853,41.229,469.676,127.954,8.122,465.512,119.642,0.670,468.203,119.159,2.292,454.369,115.423,38.397,457.939,115.022,36.961,453.854,132.373,2.232,445.378,124.258,1.249,444.885,127.410,1.015,439.860,131.176,36.834,440.065,134.618,35.079
1363854,201559,2,2024-01-12T01:31:39.663Z,4.8,0,None,0,488.544,-82.168,70.376,1628369,Jayson Tatum,0,1610612738,450.677,127.811,41.069,465.887,124.687,10.150,450.022,124.965,74.612,457.090,119.616,52.257,446.055,121.410,74.490,453.520,124.889,41.175,454.139,119.456,24.131,452.938,120.968,65.771,455.506,115.218,41.430,447.222,126.442,66.600,444.860,121.323,72.332,452.065,131.512,5.862,443.494,127.677,74.184,442.614,135.384,50.710,443.629,122.422,74.291,447.769,130.654,40.748,446.252,126.824,23.329,442.301,132.110,64.525,439.089,133.676,39.691,450.741,127.891,41.283,468.718,127.648,8.245,464.296,119.560,0.694,466.977,118.979,2.301,453.587,115.537,38.474,457.142,115.057,37.026,453.886,132.353,2.267,445.380,124.271,1.269,444.903,127.425,1.014,439.227,131.487,36.915,439.457,134.937,35.177

In [11]:
create_plotly_anim(reduced_df)